### ISSUE TITLE
Include full example

### ISSUE THREAD

**Issue by timdonovanuk** [TheByteStuff/RemoteSyslog_Service#3]
Please include what you use as a trigger. Making the screenshot about 25px higher to show this would be great :)

**Comment by TheByteStuff** [comment]
Good idea.  Traveling at the moment with limited access to internet.  Will work on getting better example information.

**Comment by boomam** [comment]
@TheByteStuff 
I'll second @timdonovanuk 's note here - 

The example showing just the action doesn't provide context on how to have this continually ship log events of a certain type to a remote syslog server.  

The example right now only shows the 'end' of the configuration in HA, not the beginning. 
Showing examples of triggers and/or conditions would be useful for the community - even if they are 'blank', as the methodology for adding automations otherwise does usually require the usage of those configs, so as a minimum I would suggest a section that says 'dont include anything for these' if that is the intended configuration.

**Comment by TheByteStuff** [comment]
Thank you for for clarifying the concern.  You are correct that my intent for this was to be used within an event to allow a message to be logged to a syslog server not to provide a mechanism for HA logs to be sent to a syslog server.  Providing an option to push HA logging to a syslog server would be interesting but definitely was not the intended use for this.

I tweaked the Readme to clarify this point.  I can create an example/screenshots of using this within context of an event if you think that would be helpful still.   I opted to depict it from the developer console to show the various fields and for use as a quick test figuring folks would plug it into their events as desired.

**Comment by boomam** [comment]
Great feedback.
I would personally suggest documentation down to a really pedantically level, but that's just me. :-p  
&nbsp;  
Maybe a small bit of text outlining what 'can' go there as a real world example would help reduce any setup issues?
